// The capability matrix: one row per capability the spec asks for, with the
// named checks (from npm run hands:check) that prove it and the gallery
// sheet that shows it. Rows are added in the same commit as the capability.
const C = {
  fullRange: 'fingers: each finger reaches its full range on every joint independently, neighbours inside natural coupling',
  thumb: 'fingers: thumb curl, spread and opposition reach their range inside the limits on both hands',
  spread: 'fingers: spread -1 to 1 reaches MCP abduction both ways on every finger, both hands',
  blend: 'fingers: control blends over the active pose, on either hand, at any time',
  countIndex: 'counting: 1 to 5 index first on both hands, right digits up, no self-penetration',
  countThumb: 'counting: 1 to 5 thumb first on both hands, right digits up, no self-penetration',
  sets: 'finger sets: all 32 combinations extend exactly the chosen digits, inside limits, no self-penetration',
  gestures: 'gestures: every registry gesture reachable, inside limits, no self-penetration, continuous at 60 fps, both hands',
  limits: 'limits: no joint passes its limit (poses and 10000 seeded blends)',
};

// Manipulation and physics checks (npm run hands:check).
const S = (label) => `capability: ${label}`;
const M = {
  pen: 'manipulation: no hand to object penetration beyond 1 mm in any capability scenario',
  grasps: 'manipulation: every grasp a scenario asks for takes hold',
  grip: 'manipulation: a held object never leaves the grip (contacts within 2 mm, the hand on what it follows within 5 mm)',
  climb: 'climbing: at least one hand attached from the first grip to the last letting go',
  contact: 'contact: pushed and pulled objects move only through contact, nothing is knocked, and nothing at rest floats',
  continuity: 'continuity: every scenario under 20 rad/s per joint, wrist under 4 cm a frame, no self-penetration over 1 mm, inside limits',
  strength: 'strength: too heavy a load or too hard a jerk slips, the fingers come off it; nothing else slips',
  weight: 'weight: a heavier load lowers the wrist further (pebble < rock < iron shot)',
  replay: 'determinism: a scripted 30 s sandbox run hashes identically when replayed',
  solver: 'budget: sim step ms, median, sandbox loaded in Node (script keys, rig, interaction, physics)',
  solverLive: 'budget: sim step ms, median, sandbox loaded live in a browser (the perf overlay figure)',
};
const P = {
  rest: 'physics: sphere, box and capsule bodies fall and come to rest on the ground and on a table, then sleep',
  bounce: 'physics: restitution bounces a ball, friction stops a slide, a resting box does not creep',
  props: 'physics: hinges keep their limits, a switch snaps to a well, a sprung button returns, a drawer holds where left',
  rope: 'physics: a rope hangs from its pinned top at its length (stretch under 2 percent)',
  contact: 'physics: a hand moves an object only through contact, the object stops the hand passing into it, a rung holds a load',
  replay: 'physics: fixed timestep and seeded, the same calls replay bit for bit',
};

export const CAPABILITIES = [
  { group: 'fingers', name: 'Curl 0 to 1 per finger', checks: [C.fullRange], sheet: 'fingers-control' },
  { group: 'fingers', name: 'Curl 0 to 1 per joint', checks: [C.fullRange], sheet: 'fingers-control' },
  { group: 'fingers', name: 'Spread', checks: [C.spread], sheet: 'fingers-control' },
  { group: 'fingers', name: 'Thumb opposition', checks: [C.thumb], sheet: 'fingers-control' },
  { group: 'fingers', name: 'Anatomically clamped', checks: [C.limits, C.fullRange, C.thumb], sheet: 'fingers-control' },
  { group: 'fingers', name: 'Either hand, independently, any time, over the active pose', checks: [C.blend], sheet: 'fingers-control' },
  { group: 'counting', name: 'Counting 1 to 5, index first', checks: [C.countIndex], sheet: '02-counting' },
  { group: 'counting', name: 'Counting 1 to 5, thumb first', checks: [C.countThumb], sheet: '02-counting' },
  { group: 'counting', name: 'Finger set: middle only', checks: [C.sets], sheet: 'fingers-sets' },
  { group: 'counting', name: 'Finger set: index and little', checks: [C.sets], sheet: 'fingers-sets' },
  { group: 'counting', name: 'Any combination from a set or mask', checks: [C.sets], sheet: 'fingers-sets' },
  ...[
    ['Relaxed', 'gestures-all'], ['Open palm', '03-gestures'], ['Spread', '03-gestures'], ['Fist, thumb outside', '03-gestures'],
    ['Point', '03-gestures'], ['OK', '03-gestures'], ['Thumbs up', '03-gestures'], ['V', '03-gestures'], ['Beckon', '03-gestures'],
    ['Wave', '03-gestures'], ['Finger drum', 'gestures-all'], ['Pebble roll', 'gestures-all'],
  ].map(([name, sheet]) => ({ group: 'gestures', name, checks: [C.gestures], sheet })),
  // Grasp and manipulation (commit 4).
  { group: 'manipulation', name: 'Grab', checks: [S('Grab, lift, carry, place'), M.grasps], sheet: '07-grab-carry-place' },
  { group: 'manipulation', name: 'Hold under motion', checks: [S('Grab, lift, carry, place'), M.grip], sheet: '07-grab-carry-place' },
  { group: 'manipulation', name: 'Carry', checks: [S('Grab, lift, carry, place')], sheet: '07-grab-carry-place' },
  { group: 'manipulation', name: 'Place', checks: [S('Grab, lift, carry, place'), M.contact], sheet: '07-grab-carry-place' },
  { group: 'manipulation', name: 'Release', checks: [S('Grab, lift, carry, place'), M.pen], sheet: '07-grab-carry-place' },
  { group: 'manipulation', name: 'Throw', checks: [S('Throw and catch')], sheet: '08-throw-catch' },
  { group: 'manipulation', name: 'Catch', checks: [S('Throw and catch')], sheet: '08-throw-catch' },
  { group: 'grips', name: 'Pad pinch', checks: [S('Pad pinch on three sizes')], sheet: '04-pinch-tripod' },
  { group: 'grips', name: 'Tripod', checks: [S('Tripod on three sizes')], sheet: '04-pinch-tripod' },
  { group: 'grips', name: 'Lateral pinch', checks: [S('Lateral pinch')], sheet: 'cap-lateralPinch' },
  { group: 'grips', name: 'Hook', checks: [S('Hook: a bag by its strap')], sheet: 'cap-hook' },
  { group: 'grips', name: 'Power cylinder grip', checks: [S('Power grip on a handle')], sheet: '05-power-spherical' },
  { group: 'grips', name: 'Spherical grip', checks: [S('Spherical grip on a ball')], sheet: '05-power-spherical' },
  { group: 'manipulation', name: 'Two-hand grip on one object', checks: [S('Two-hand grip on one box')], sheet: '06-two-hand-handover' },
  { group: 'manipulation', name: 'Handover between hands', checks: [S('Handover between hands')], sheet: '06-two-hand-handover' },
  { group: 'manipulation', name: 'In-hand roll', checks: [S('In-hand roll')], sheet: 'cap-inHandRoll' },
  { group: 'manipulation', name: 'In-hand spin', checks: [S('In-hand spin')], sheet: 'cap-inHandSpin' },
  { group: 'props', name: 'Press a button', checks: [S('Press a button')], sheet: '10-props' },
  { group: 'props', name: 'Flip a switch', checks: [S('Flip a switch')], sheet: '10-props' },
  { group: 'props', name: 'Pull a lever', checks: [S('Pull a lever')], sheet: '10-props' },
  { group: 'props', name: 'Turn a knob', checks: [S('Turn a knob')], sheet: '10-props' },
  { group: 'props', name: 'Open and close a drawer', checks: [S('Open and close a drawer')], sheet: '10-props' },
  { group: 'props', name: 'Push a crate', checks: [S('Push a crate'), M.contact], sheet: '09-push-drag' },
  { group: 'props', name: 'Drag a crate', checks: [S('Drag a crate'), M.contact], sheet: '09-push-drag' },
  { group: 'climbing', name: 'Hang from a rung', checks: [S('Hang from a rung'), M.climb], sheet: 'cap-hang' },
  { group: 'climbing', name: 'Climb hand over hand', checks: [S('Climb hand over hand'), M.climb], sheet: '11-climb' },
  { group: 'climbing', name: 'Hold a rope', checks: [S('Hold a rope'), M.climb], sheet: 'cap-rope' },
  { group: 'strength', name: 'Grip strength and slip', checks: [M.strength, S('Slip: too heavy for the grip'), S('Slip: accelerated too hard')], sheet: 'cap-slipHeavy' },
  { group: 'strength', name: 'Weight reads in the arms', checks: [M.weight], sheet: 'cap-slipJerk' },
  { group: 'manipulation', name: 'Every manipulation clean: no penetration, grips hold, continuous', checks: [M.pen, M.grip, M.continuity], sheet: '07-grab-carry-place' },
  // Interaction physics (commit 5).
  { group: 'physics', name: 'Rigid bodies: sphere, box, capsule with mass, gravity, friction, restitution', checks: [P.rest, P.bounce], sheet: 'cap-sphericalGrip' },
  { group: 'physics', name: 'Hinge (lever, switch, knob)', checks: [P.props, S('Pull a lever'), S('Flip a switch'), S('Turn a knob')], sheet: '10-props' },
  { group: 'physics', name: 'Slider (drawer, button)', checks: [P.props, S('Open and close a drawer'), S('Press a button')], sheet: '10-props' },
  { group: 'physics', name: 'Fixed rungs', checks: [P.contact, S('Climb hand over hand')], sheet: '11-climb' },
  { group: 'physics', name: 'Rope as a chain of points', checks: [P.rope, S('Hold a rope')], sheet: 'cap-rope' },
  { group: 'physics', name: 'Hands move objects, objects resist hands', checks: [P.contact, M.contact, S('Push a crate')], sheet: '09-push-drag' },
  { group: 'physics', name: 'Climbing moves the body anchor between hands, one hand always attached', checks: [M.climb], sheet: '11-climb' },
  { group: 'physics', name: 'Deterministic: fixed timestep, seeded, replays hash identically', checks: [P.replay, M.replay], sheet: '07-grab-carry-place' },
  { group: 'budget', name: 'Sim step time with the sandbox loaded, in Node and live', checks: [M.solver, M.solverLive], sheet: '07-grab-carry-place' },
];
